"use client";

import { useEffect, useMemo, useState } from "react";
import { EmptyState, ProductShell, StatusBadge } from "@/app/components/product-shell";
import { API_BASE, secureFetch, redirectIfOnboardingRequired } from "@/app/lib/api";

type SnapshotArea = {
  areaId: string;
  realR: number;
  potentialP: number;
  area?: { id: string; name: string };
};
type Snapshot = {
  id: string;
  userId: string;
  rankingGlobal: number;
  reason: string;
  createdAt: string;
  areas: SnapshotArea[];
};

const formatDate = (value: string) => {
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return "Unknown date";
  }
  return parsed.toLocaleDateString("en-US", { month: "short", day: "2-digit", year: "numeric" });
};

export default function UserPerformancePage() {
  const [current, setCurrent] = useState<Snapshot | null>(null);
  const [history, setHistory] = useState<Snapshot[]>([]);
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [authHint, setAuthHint] = useState<string | null>(null);

  const sortedHistory = useMemo(
    () => history.slice().sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()),
    [history],
  );

  const loadProfile = async () => {
    setLoading(true);
    setMessage(null);
    setAuthHint(null);

    const [currentRes, historyRes] = await Promise.all([
      secureFetch(`${API_BASE}/performance/profile/current`, { credentials: "include" }),
      secureFetch(`${API_BASE}/performance/profile/history`, { credentials: "include" }),
    ]);

    if (!currentRes.ok || !historyRes.ok) {
      if (currentRes.status === 401 || historyRes.status === 401) {
        setAuthHint("Sign in to view your performance profile.");
      } else if (currentRes.status === 404) {
        setCurrent(null);
        setHistory([]);
      } else {
        setMessage("Unable to load performance profile.");
      }
      setLoading(false);
      return;
    }

    setCurrent((await currentRes.json()) as Snapshot);
    setHistory((await historyRes.json()) as Snapshot[]);
    setLoading(false);
  };

  useEffect(() => {
    void (async () => {
      if (!(await redirectIfOnboardingRequired())) {
        await loadProfile();
      }
    })();
  }, []);

  return (
    <ProductShell
      eyebrow="Athlete workspace"
      title="Performance profile"
      description="Review your latest ranking, area-level real and potential values, and the snapshot history generated by closed cycles."
      actions={
        <button className="pf-button-secondary" type="button" onClick={() => loadProfile()}>
          Refresh
        </button>
      }
      stats={[
        { label: "Global ranking", value: loading ? "..." : current?.rankingGlobal ?? "-", tone: "accent" },
        { label: "Areas tracked", value: current?.areas.length ?? 0, tone: "success" },
        { label: "Snapshots", value: history.length, tone: "warning" },
      ]}
    >
      {authHint && <div className="pf-alert warning">{authHint}</div>}
      {message && <div className="pf-alert">{message}</div>}

      <section className="pf-panel">
        <div className="pf-panel-header">
          <div>
            <h2>Current snapshot</h2>
            <p className="pf-muted">Real measures current execution. Potential tracks reachable next-level capacity.</p>
          </div>
          {current && <StatusBadge tone="success">{formatDate(current.createdAt)}</StatusBadge>}
        </div>
        {current ? (
          <div className="pf-grid">
            {current.areas.map((area) => (
              <article key={area.areaId} className="pf-card">
                <div className="pf-card-top">
                  <div>
                    <h3>{area.area?.name ?? "Area"}</h3>
                    <p className="pf-muted pf-mono">{area.areaId.slice(0, 8)}</p>
                  </div>
                </div>
                <div className="pf-row">
                  <span>Real</span>
                  <strong>{area.realR.toFixed(1)}</strong>
                </div>
                <div className="pf-row">
                  <span>Potential</span>
                  <strong>{area.potentialP.toFixed(1)}</strong>
                </div>
              </article>
            ))}
          </div>
        ) : (
          !loading && (
            <EmptyState
              title="No profile yet"
              description="Complete and close a published questionnaire to generate the first performance snapshot."
            />
          )
        )}
      </section>

      <section className="pf-panel">
        <div className="pf-panel-header">
          <div>
            <h2>Snapshot timeline</h2>
            <p className="pf-muted">Each closed cycle appends a new historical profile point.</p>
          </div>
        </div>
        <div className="pf-stack">
          {sortedHistory.map((snapshot) => (
            <article key={snapshot.id} className="pf-card">
              <div className="pf-card-top">
                <div>
                  <h3>Ranking {snapshot.rankingGlobal}</h3>
                  <p className="pf-muted">{snapshot.reason}</p>
                </div>
                <div className="pf-stack">
                  <StatusBadge>{formatDate(snapshot.createdAt)}</StatusBadge>
                  <span className="pf-muted pf-mono">{snapshot.id.slice(0, 8)}</span>
                </div>
              </div>
            </article>
          ))}
          {!loading && sortedHistory.length === 0 && (
            <EmptyState title="No history yet" description="Snapshot history appears after closing performance cycles." />
          )}
        </div>
      </section>
    </ProductShell>
  );
}
