ALTER TABLE "TrainingPlanRelease" ADD COLUMN "startsOn" DATE, ADD COLUMN "endsOn" DATE, ADD COLUMN "windowDays" INTEGER NOT NULL DEFAULT 14;
ALTER TABLE "TrainingPlanRelease" ADD CONSTRAINT "TrainingPlanRelease_window_check" CHECK (("startsOn" IS NULL AND "endsOn" IS NULL) OR ("startsOn" IS NOT NULL AND "endsOn" IS NOT NULL AND "endsOn" = "startsOn" + 13 AND "windowDays" = 14));
CREATE INDEX "TrainingPlanRelease_rolling_sweep_idx" ON "TrainingPlanRelease" ("endsOn") WHERE "cycleStatus" = 'PUBLISHED' AND "lifecycleManaged" = true;
-- Existing accepted discovery snapshots remain immutable; missing values can be completed in the athlete profile.
UPDATE "OnboardingQuestionTemplate" SET "optionsJson" = "optionsJson" || '{"contextKey":"general_training_frequency"}'::jsonb, "updatedAt" = CURRENT_TIMESTAMP WHERE "key" = 'pf4_frequency' AND NOT ("optionsJson" ? 'contextKey');
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","label","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES
('pf4_training_days_available','pf4_training_days_available','DISCOVERY','Quanti giorni alla settimana puoi realisticamente allenarti?','SELECT','{"type":"single_choice","contextKey":"training_days_available","options":[{"id":"1","label":"1 giorno","value":1},{"id":"2","label":"2 giorni","value":2},{"id":"3","label":"3 giorni","value":3},{"id":"4","label":"4 giorni","value":4},{"id":"5","label":"5 giorni","value":5},{"id":"6","label":"6 giorni","value":6},{"id":"7","label":"7 giorni","value":7}]}'::jsonb,true,42,true,CURRENT_TIMESTAMP),
('pf4_training_session_duration','pf4_training_session_duration','DISCOVERY','Quanto tempo puoi dedicare mediamente a una sessione?','SELECT','{"type":"single_choice","contextKey":"training_session_duration","options":[{"id":"30","label":"30 minuti","value":30},{"id":"45","label":"45 minuti","value":45},{"id":"60","label":"60 minuti","value":60},{"id":"90","label":"90 minuti","value":90},{"id":"120","label":"120+ minuti","value":120}]}'::jsonb,true,43,true,CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO NOTHING;
