ALTER TABLE "AthleteDiscovery"
 ADD COLUMN "assessmentAnswers" JSONB NOT NULL DEFAULT '{}',
 ADD COLUMN "currentQuestion" INTEGER NOT NULL DEFAULT 0,
 ADD COLUMN "operationAt" TIMESTAMP(3),
 ADD COLUMN "baselineId" TEXT,
 ADD COLUMN "programDurationWeeks" INTEGER,
 ADD COLUMN "durationSelectedAt" TIMESTAMP(3);
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","areaId","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_age','pf4_age','DISCOVERY',NULL,'Quanti anni hai?',NULL,'SELECT','{"type": "single_choice", "contextKey": "general_age_range", "options": [{"id": "0", "label": "18-29", "value": "18-29"}, {"id": "1", "label": "30-39", "value": "30-39"}, {"id": "2", "label": "40-49", "value": "40-49"}, {"id": "3", "label": "50+", "value": "50+"}], "ui": {"presentation": "cards", "columns": 2}}'::jsonb,true,25,true,CURRENT_TIMESTAMP) ON CONFLICT ("key") DO NOTHING;
UPDATE "OnboardingQuestionTemplate" SET "orderIndex"=27 WHERE "key"='pf4_motivation';
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","areaId","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_limitations','pf4_limitations','DISCOVERY',NULL,'Hai dolori o limitazioni fisiche?','Cambia cosa ti proponiamo e quanto puoi migliorare in poche settimane.','SELECT','{"type": "single_choice", "contextKey": "general_health_status", "options": [{"id": "0", "label": "Nessuna", "value": "Nessuna"}, {"id": "1", "label": "Gomito o spalla", "value": "Gomito o spalla"}, {"id": "2", "label": "Ginocchio o caviglia", "value": "Ginocchio o caviglia"}, {"id": "3", "label": "Schiena", "value": "Schiena"}]}'::jsonb,true,45,true,CURRENT_TIMESTAMP) ON CONFLICT ("key") DO NOTHING;
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","areaId","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_event_date','pf4_event_date','DISCOVERY',NULL,'Quando sarà?','Se non hai una data, puoi continuare senza indicarla.','TEXT','{"type": "date", "contextKey": "general_event_date"}'::jsonb,false,75,true,CURRENT_TIMESTAMP) ON CONFLICT ("key") DO NOTHING;
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","areaId","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_weight','pf4_weight','DISCOVERY',NULL,'Quanto pesi?','Serve per calibrare i carichi, non per giudicarti.','NUMBER','{"type": "number", "contextKey": "general_weight_kg", "min": 35, "max": 200, "step": 0.1, "ui": {"unit": "kg"}}'::jsonb,true,80,true,CURRENT_TIMESTAMP) ON CONFLICT ("key") DO NOTHING;
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","areaId","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_height','pf4_height','DISCOVERY',NULL,'Quanto misuri?',NULL,'NUMBER','{"type": "number", "contextKey": "general_height_cm", "min": 130, "max": 220, "step": 1, "ui": {"unit": "cm"}}'::jsonb,true,90,true,CURRENT_TIMESTAMP) ON CONFLICT ("key") DO NOTHING;
INSERT INTO "Area" ("id", "name") VALUES ('pf4-driver-0', 'Tecnico-tattica') ON CONFLICT ("name") DO NOTHING;
INSERT INTO "Area" ("id", "name") VALUES ('pf4-driver-1', 'Preparazione atletica') ON CONFLICT ("name") DO NOTHING;
INSERT INTO "Area" ("id", "name") VALUES ('pf4-driver-2', 'Allenamento mentale') ON CONFLICT ("name") DO NOTHING;
INSERT INTO "Area" ("id", "name") VALUES ('pf4-driver-3', 'Nutrizione') ON CONFLICT ("name") DO NOTHING;
INSERT INTO "Area" ("id", "name") VALUES ('pf4-driver-4', 'Equipaggiamento') ON CONFLICT ("name") DO NOTHING;
INSERT INTO "Area" ("id", "name") VALUES ('pf4-driver-5', 'Fisioterapia') ON CONFLICT ("name") DO NOTHING;
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","areaId","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_padel_assessment_1','pf4_padel_assessment_1','AREA',(SELECT "id" FROM "Area" WHERE "name"='Tecnico-tattica' LIMIT 1),'Quando arrivi a rete per chiudere il punto, cosa succede più spesso?',NULL,'SELECT','{"sportKey": "PADEL", "options": [{"value": "0", "label": "Chiudo e scelgo l''angolo prima di colpire", "score": 100}, {"value": "1", "label": "Chiudo, ma senza decidere dove mando la palla", "score": 67}, {"value": "2", "label": "Rimando la palla e aspetto l''errore altrui", "score": 33}, {"value": "3", "label": "Sbaglio o mi faccio passare", "score": 0}]}'::jsonb,true,1,true,CURRENT_TIMESTAMP) ON CONFLICT ("key") DO NOTHING;
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","areaId","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_padel_assessment_2','pf4_padel_assessment_2','AREA',(SELECT "id" FROM "Area" WHERE "name"='Tecnico-tattica' LIMIT 1),'Il tuo colpo dopo la parete di fondo.',NULL,'SELECT','{"sportKey": "PADEL", "options": [{"value": "0", "label": "Pulito: controllo altezza e direzione", "score": 100}, {"value": "1", "label": "Esce, ma senza direzione precisa", "score": 67}, {"value": "2", "label": "A volte la lascio passare e perdo il punto", "score": 33}, {"value": "3", "label": "Lo evito, gioco quasi solo di volo", "score": 0}]}'::jsonb,true,2,true,CURRENT_TIMESTAMP) ON CONFLICT ("key") DO NOTHING;
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","areaId","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_padel_assessment_3','pf4_padel_assessment_3','AREA',(SELECT "id" FROM "Area" WHERE "name"='Preparazione atletica' LIMIT 1),'Al terzo set, come stai fisicamente?',NULL,'SELECT','{"sportKey": "PADEL", "options": [{"value": "0", "label": "Gambe e lucidità intatte", "score": 100}, {"value": "1", "label": "Cala la velocità ma tengo il livello", "score": 67}, {"value": "2", "label": "Comincio a sbagliare per stanchezza", "score": 33}, {"value": "3", "label": "Vado in riserva, gioco per finire", "score": 0}]}'::jsonb,true,3,true,CURRENT_TIMESTAMP) ON CONFLICT ("key") DO NOTHING;
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","areaId","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_padel_assessment_4','pf4_padel_assessment_4','AREA',(SELECT "id" FROM "Area" WHERE "name"='Preparazione atletica' LIMIT 1),'Quante volte a settimana ti alleni fuori dal campo?',NULL,'SELECT','{"sportKey": "PADEL", "options": [{"value": "0", "label": "Tre o più, con un programma", "score": 100}, {"value": "1", "label": "Una o due", "score": 67}, {"value": "2", "label": "Ogni tanto, senza continuità", "score": 33}, {"value": "3", "label": "Mai, gioco e basta", "score": 0}]}'::jsonb,true,4,true,CURRENT_TIMESTAMP) ON CONFLICT ("key") DO NOTHING;
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","areaId","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_padel_assessment_5','pf4_padel_assessment_5','AREA',(SELECT "id" FROM "Area" WHERE "name"='Allenamento mentale' LIMIT 1),'Sei sotto 4-5 nel set decisivo. Cosa fai?',NULL,'SELECT','{"sportKey": "PADEL", "options": [{"value": "0", "label": "Alzo la concentrazione e semplifico le scelte", "score": 100}, {"value": "1", "label": "Resto lucido ma gioco solo in difesa", "score": 67}, {"value": "2", "label": "Comincio a strafare per chiudere subito", "score": 33}, {"value": "3", "label": "Mi innervosisco e perdo il filo", "score": 0}]}'::jsonb,true,5,true,CURRENT_TIMESTAMP) ON CONFLICT ("key") DO NOTHING;
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","areaId","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_padel_assessment_6','pf4_padel_assessment_6','AREA',(SELECT "id" FROM "Area" WHERE "name"='Allenamento mentale' LIMIT 1),'Dopo un errore grave in un punto importante.',NULL,'SELECT','{"sportKey": "PADEL", "options": [{"value": "0", "label": "Reset immediato: punto nuovo", "score": 100}, {"value": "1", "label": "Mi servono un paio di punti per rientrare", "score": 67}, {"value": "2", "label": "Ci penso per tutto il game", "score": 33}, {"value": "3", "label": "Mi condiziona il resto della partita", "score": 0}]}'::jsonb,true,6,true,CURRENT_TIMESTAMP) ON CONFLICT ("key") DO NOTHING;
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","areaId","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_padel_assessment_7','pf4_padel_assessment_7','AREA',(SELECT "id" FROM "Area" WHERE "name"='Nutrizione' LIMIT 1),'Cosa mangi nelle tre ore prima di giocare?',NULL,'SELECT','{"sportKey": "PADEL", "options": [{"value": "0", "label": "Un pasto pianificato, sempre lo stesso schema", "score": 100}, {"value": "1", "label": "Qualcosa di leggero, deciso sul momento", "score": 67}, {"value": "2", "label": "Quello che capita", "score": 33}, {"value": "3", "label": "Niente, gioco a stomaco vuoto", "score": 0}]}'::jsonb,true,7,true,CURRENT_TIMESTAMP) ON CONFLICT ("key") DO NOTHING;
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","areaId","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_padel_assessment_8','pf4_padel_assessment_8','AREA',(SELECT "id" FROM "Area" WHERE "name"='Nutrizione' LIMIT 1),'E dopo la partita?',NULL,'SELECT','{"sportKey": "PADEL", "options": [{"value": "0", "label": "Reintegro entro un''ora", "score": 100}, {"value": "1", "label": "Mangio quando torno a casa", "score": 67}, {"value": "2", "label": "Bevo qualcosa e basta", "score": 33}, {"value": "3", "label": "Non ci penso", "score": 0}]}'::jsonb,true,8,true,CURRENT_TIMESTAMP) ON CONFLICT ("key") DO NOTHING;
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","areaId","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_padel_assessment_9','pf4_padel_assessment_9','AREA',(SELECT "id" FROM "Area" WHERE "name"='Equipaggiamento' LIMIT 1),'Come hai scelto la pala che usi?',NULL,'SELECT','{"sportKey": "PADEL", "options": [{"value": "0", "label": "Su peso, bilanciamento e il mio tipo di gioco", "score": 100}, {"value": "1", "label": "Me l''ha consigliata chi se ne intende", "score": 67}, {"value": "2", "label": "Per estetica o per prezzo", "score": 33}, {"value": "3", "label": "Non so nemmeno che pala ho", "score": 0}]}'::jsonb,true,9,true,CURRENT_TIMESTAMP) ON CONFLICT ("key") DO NOTHING;
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","areaId","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_padel_assessment_10','pf4_padel_assessment_10','AREA',(SELECT "id" FROM "Area" WHERE "name"='Equipaggiamento' LIMIT 1),'Scarpe e overgrip.',NULL,'SELECT','{"sportKey": "PADEL", "options": [{"value": "0", "label": "Cambio secondo l''usura", "score": 100}, {"value": "1", "label": "Cambio quando sono consumate", "score": 67}, {"value": "2", "label": "Raramente", "score": 33}, {"value": "3", "label": "Non ci ho mai pensato", "score": 0}]}'::jsonb,true,10,true,CURRENT_TIMESTAMP) ON CONFLICT ("key") DO NOTHING;
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","areaId","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_padel_assessment_11','pf4_padel_assessment_11','AREA',(SELECT "id" FROM "Area" WHERE "name"='Fisioterapia' LIMIT 1),'Dolori ricorrenti dopo aver giocato?',NULL,'SELECT','{"sportKey": "PADEL", "options": [{"value": "0", "label": "Nessuno", "score": 100}, {"value": "1", "label": "Qualche rigidità che passa in un giorno", "score": 67}, {"value": "2", "label": "Un fastidio ricorrente: gomito, spalla o ginocchio", "score": 33}, {"value": "3", "label": "Dolore che mi limita in campo", "score": 0}]}'::jsonb,true,11,true,CURRENT_TIMESTAMP) ON CONFLICT ("key") DO NOTHING;
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","areaId","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_padel_assessment_12','pf4_padel_assessment_12','AREA',(SELECT "id" FROM "Area" WHERE "name"='Fisioterapia' LIMIT 1),'La tua mobilità di spalla e anca.',NULL,'SELECT','{"sportKey": "PADEL", "options": [{"value": "0", "label": "Lavorata: faccio mobilità con regolarità", "score": 100}, {"value": "1", "label": "Discreta, ma senza lavoro specifico", "score": 67}, {"value": "2", "label": "Limitata, me ne accorgo in campo", "score": 33}, {"value": "3", "label": "Molto limitata", "score": 0}]}'::jsonb,true,12,true,CURRENT_TIMESTAMP) ON CONFLICT ("key") DO NOTHING;
