CREATE TABLE "AthleteDiscovery" (
  "userId" TEXT NOT NULL PRIMARY KEY,
  "version" BIGINT NOT NULL,
  "draft" JSONB NOT NULL,
  "configuration" JSONB NOT NULL,
  "phase" TEXT NOT NULL DEFAULT 'CONSENTS',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "AthleteDiscovery_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Public reads never seed or mutate configuration. Existing sports are reused.
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_sport','pf4_sport','DISCOVERY','Qual è il tuo sport?','Partiamo da quello che ti piace fare.','SELECT','{"target": "sportId", "type": "single_choice", "ui": {"presentation": "compact_cards"}}'::jsonb,true,10,true,CURRENT_TIMESTAMP);
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_specialization','pf4_specialization','DISCOVERY','Qual è la tua specialità?',NULL,'SELECT','{"target": "specializationId", "type": "single_choice", "ui": {"presentation": "compact_cards"}}'::jsonb,true,20,true,CURRENT_TIMESTAMP);
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_experience','pf4_experience','DISCOVERY','Da quanto tempo pratichi?',NULL,'SELECT','{"type": "single_choice", "options": [{"id": "0", "label": "Meno di un anno", "value": "Meno di un anno"}, {"id": "1", "label": "1-3 anni", "value": "1-3 anni"}, {"id": "2", "label": "3-5 anni", "value": "3-5 anni"}, {"id": "3", "label": "Più di 5 anni", "value": "Più di 5 anni"}]}'::jsonb,true,30,true,CURRENT_TIMESTAMP);
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_frequency','pf4_frequency','DISCOVERY','Quante volte ti alleni a settimana?','Consideriamo i tuoi impegni, senza sostituirli.','SELECT','{"type": "single_choice", "options": [{"id": "0", "label": "1-2 volte", "value": "1-2 volte"}, {"id": "1", "label": "3-4 volte", "value": "3-4 volte"}, {"id": "2", "label": "5 o più volte", "value": "5 o più volte"}]}'::jsonb,true,40,true,CURRENT_TIMESTAMP);
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_goal','pf4_goal','DISCOVERY','Qual è il tuo obiettivo principale?','Il tuo percorso comincia da questo.','SELECT','{"target": "goalId", "type": "single_choice", "options": [{"id": "0", "label": "Migliorare la tecnica", "value": "Migliorare la tecnica"}, {"id": "1", "label": "Aumentare la resistenza", "value": "Aumentare la resistenza"}, {"id": "2", "label": "Perdere peso", "value": "Perdere peso"}, {"id": "3", "label": "Prevenire gli infortuni", "value": "Prevenire gli infortuni"}]}'::jsonb,true,50,true,CURRENT_TIMESTAMP);
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_motivation','pf4_motivation','DISCOVERY','Perché pratichi sport?','Non c''è una risposta migliore delle altre.','SELECT','{"type": "single_choice", "options": [{"id": "0", "label": "Per vincere", "value": "Per vincere"}, {"id": "1", "label": "Per restare in forma", "value": "Per restare in forma"}, {"id": "2", "label": "Per stare in compagnia", "value": "Per stare in compagnia"}, {"id": "3", "label": "Per staccare dalla giornata", "value": "Per staccare dalla giornata"}]}'::jsonb,true,60,true,CURRENT_TIMESTAMP);
INSERT INTO "OnboardingQuestionTemplate" ("id","key","scope","label","helpText","inputType","optionsJson","required","orderIndex","isActive","updatedAt") VALUES ('pf4_event','pf4_event','DISCOVERY','Hai un evento importante in arrivo?','Avere una data ti aiuta a restare costante.','SELECT','{"type": "single_choice", "options": [{"id": "0", "label": "Un torneo", "value": "Un torneo"}, {"id": "1", "label": "Un campionato", "value": "Un campionato"}, {"id": "2", "label": "Una vacanza", "value": "Una vacanza"}, {"id": "3", "label": "Nessuno in particolare", "value": "Nessuno in particolare"}]}'::jsonb,true,70,true,CURRENT_TIMESTAMP);
